### PR TITLE
py3 updates and parallelism

### PR DESCRIPTION
**Pull request by sbailey**
This PR brings redmonster changes from DESI back into Tim's copy to try to keep us in sync.  Changes include:
- updates for python 3.5, while still retaining python 2.7 compatibility.  The vast majority of these changes are to add parentheses to `print` and change `xrange` to `range`.
- New multiprocessing-based parallelism in `zfinder.py`.
- some sdss-specific scripts like `bin/zfind_dr13_cmass` and `bin/zfind_dr14_lrg_fillin` were dropped.  I don't know if these were genuinely deprecated or whether they were lost in overzealous DESI cleanup.  I would recommend that experiment specific special purpose scripts like this shouldn't be in the bin/ directory of a package that aspires to being cross project general purpose.
- Reviewing the diffs, there were some changes that don't seem necessary, e.g. `redmonster/sandbox/verify_sequels.py` line 2484:

```
-        p.legend(loc=2, prop={'size':14})
+        p.legend(loc=2)
```

Let us know if you want us to put those back.

I'd like to make a 1.2.0 tag based on this version.

### CODE REVIEW

**Comment by timahutchinson** [comment]
I agree with dropping SDSS-specific scripts from the repo.

A quick look through the diffs shows many changes that were made to timahutchinson/redmonster after it was forked into desihub that were never moved forward (e.g. template groups), and this PR reverts those entirely.  Those should be added to the DESI version before a merge.

**Comment by sbailey** [comment]
1. We definitely don't intend to revert features like template groups.
2. github says that desihub/redmonster is only ahead of timahutchinson/redmonster, and no commits behind.  I also did an explicit merge of timahutchinson/redmonster/master into desihub/redmonster/master prior to opening this PR, so I'm confused about where those changes went.
3. I'll investigate...

Can you point me to the template group code on your side to make it easier for me to find where it went in the history on the desihub side?

**Comment by sbailey** [comment]
This problem has exceeded my git-fu.  I've called in reinforcements but they aren't available until tomorrow...

desihub/master has some template group code but not all.  I think the merge problem has arisen since the template group changes were implemented as a different set of commits on desihub instead of implementing them for timahutchinson and then merging from there to desihub.  git is thinking the some incomplete changes on the desihub side were actually intended to supersede the more complete implementation on the timahutchinson side.  ugh.

Thanks for catching this problem; don't merge yet...

**Comment by timahutchinson** [comment]
I'll wait to merge until it gets straightened out.  There seems to be some functionality that got lost along the way, and some bugs were introduced.

**Comment by sbailey** [comment]
Ted and I found the cause of the missing changes (a revert of a merge while trying to recover a working state for the python 3 transition).  I'll close this PR and open a new one when we get it sorted out.

**Pull request closed without merging**
